{% set version = "1.0" %}
package:
  name: mm2-fast
  version: {{ version }}

source:
  - url: https://github.com/bwa-mem2/mm2-fast/releases/download/mm2-fast-v{{ version }}/Source_code_including_submodules.tar.gz
    sha256: 7517E94FC9EC1DB5F5C75D44280C303BD050FF3E630B44265E6920E9EC16D94D
  
build:
  number: 1

requirements:
  build:
    - make
    - {{ compiler('cxx') }}
  host:
    - zlib

test:
  commands:
    - minimap2 --version


about:
  home: https://github.com/bwa-mem2/mm2-fast
  license: MIT
  license_file: LICENSE.txt
  summary: mm2-fast-v1.0 faster version of minimap2

